export const LOCAL_PROVIDER_ERROR_CODES = {
  PARSE_ERROR: "PARSE_ERROR",
  SCHEMA_ERROR: "SCHEMA_ERROR",
  FLAG_NOT_FOUND: "FLAG_NOT_FOUND",
  TYPE_MISMATCH: "TYPE_MISMATCH",
  INVALID_CONTEXT: "INVALID_CONTEXT",
  OVERRIDE_PARSE_ERROR: "OVERRIDE_PARSE_ERROR",
  PROVIDER_NOT_READY: "PROVIDER_NOT_READY",
  AUDIT_SINK_ERROR: "AUDIT_SINK_ERROR"
} as const;

export type LocalProviderErrorCode =
  (typeof LOCAL_PROVIDER_ERROR_CODES)[keyof typeof LOCAL_PROVIDER_ERROR_CODES];
